services:
  # Web Service with Docker
  - type: web
    name: qr-backend-2
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        value: your-super-secret-key-change-this-in-production-2024
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: ALLOWED_ORIGINS
        value: https://qr-admin-frontend-nu.vercel.app,https://qr-user-frontend-tunz.vercel.app
